%%

In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
import os
np.set_printoptions(suppress=True)
os.system('cls' if os.name == 'nt' else 'clear') # Clean the console
input_loc = os.getcwd() 

In [3]:
X_train = list()
X_test = list()
y_train = list()
y_test = list()

In [4]:
languages = ['e', 'j', 's']
for class_index in range(3):
    for file_index in range(10):
        file_name = input_loc +'/languageID/'+ languages[class_index] + str(file_index)+'.txt'
        X_train.append(open(file_name,'r').read()) # Read all text while ignoring "new line"
        y_train.append(class_index)
    for file_index in range(10,20):
        file_name = input_loc +'/languageID/'+ languages[class_index] + str(file_index)+'.txt'
        X_test.append(open(file_name,'r').read()) # Read all text while ignoring "new line"
        y_test.append(class_index)

In [5]:
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [6]:
vectorizer = CountVectorizer(analyzer='char')

In [7]:
X_train = vectorizer.fit_transform(X_train).toarray()
X_test = vectorizer.fit_transform(X_test).toarray()
# print(X_train[:5,0:10])

In [8]:
# Swap "space" to the last column of the feature set
X_train = np.concatenate((X_train[:,1:],X_train[:,0].reshape((len(X_train[:,-1]),1))), axis=1)
X_test = np.concatenate((X_test[:,1:],X_test[:,0].reshape((len(X_test[:,-1]),1))), axis=1)

In [9]:
from naive_bayes import MultinomialNaiveBayes

In [10]:
mnb = MultinomialNaiveBayes(X_train, y_train)
mnb.train(X_train, y_train)

In [11]:
y_pred = mnb.predict(X_test)
print(y_pred)
print(confusion_matrix(y_test, y_pred))

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
